name: CorpusPaper
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - notebook
  - dash
  - jupyter
  - rise
  - jupyter-dash
  - dash-core-components
  - dash_cytoscape
  - dash-html-components
  - scikit-learn
  - dash-table
